export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_XML_DATA_SUCCESS = 'GET_XML_DATA_SUCCESS';
export const GET_XML_DATA_FAILURE = 'GET_XML_DATA_FAILURE';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const CALCULATE_INITIAL_DATA = 'CALCULATE_INITIAL_DATA';

export const UPDATE_STORE = 'UPDATE_STORE';
